SELECT DEPTNO, SUM(SAL) 합계, FLOOR(AVG(SAL)) 평균, COUNT(*) 인원수
FROM EMP
WHERE SAL > 2800
GROUP BY DEPTNO
ORDER BY DEPTNO ASC;


SELECT DEPTNO, SUM(SAL) 합계, FLOOR(AVG(SAL)) 평균, COUNT(*) 인원수
FROM EMP
GROUP BY DEPTNO
HAVING FLOOR(AVG(SAL)) > 2800
ORDER BY DEPTNO ASC;



----------------------------------
SELECT ROWNUM, ENAME, SAL
FROM EMP
WHERE ROWNUM <= 3
ORDER BY SAL DESC;

SELECT ROWNUM NO, ENAME, SAL
FROM (
        SELECT ENAME, SAL
         FROM emp
         ORDER BY sal DESC
      )
 WHERE ROWNUM <=3
 
 -----------------------------
 
SELECT TO_DATE('20/10/13', 'YY-MM-DD')
FROM DUAL

SELECT TO_CHAR(SYSDATE, 'YY-MM-DD')
FROM DUAL



SELECT TO_CHAR(TO_DATE('190505'),'""YYYY"년 "MM"월 "DD"일"')
FROM DUAL

SELECT TO_CHAR(SYSDATE, '""YYYY"년 "MM"월 "DD"일"')
FROM DUAL
----------------------------------------

SELECT CONCAT(CONCAT(EMPNO,','),ENAME)
FROM EMP

SELECT
  CASE MERIT_RATING

  WHEN 'A' THEN SALARY * 0.2

  WHEN 'B' THEN SALARY * 0.15

  WHEN 'C' THEN SALARY * 0.1

  ELSE 0

  END

FROM DUAL